FROM  node
WORKDIR /graphql-example/client
COPY package.json .
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
    else npm install --only=production; \
    fi
COPY . ./
RUN chmod 777 ./node_modules/