FROM  node
WORKDIR /graphql-example/client
COPY package.json .
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
    else npm install --only=production; \
    fi
COPY . ./
EXPOSE $REACT_PORT
CMD ["node", "app.js"]
RUN chmod 777 /graphql-example/client/node_modules/