FROM  node:17
WORKDIR /graphql-example/client
COPY package.json .
ARG SERVER_ENV
RUN if [ "$SERVER_ENV" = "development" ]; \
        then npm install; \
    else npm install --only=production; \
    fi
COPY . ./
RUN chmod 777 ./node_modules/