version: '3'
services:
  graphql-server:
    build:
      context: ./server
      args: 
        NODE_ENV: development
    env_file:
      - ./.envdev
    ports:
      - "4001:4001"
    volumes:
      - ./:/graphql-example
      - /graphql-example/server/node_modules
    command: npm run dev