version: '3'
services:
  graphql-server:
    build:
      context: ./
      args: 
        NODE_ENV: production
    env_file:
      - ./.envprod
    ports:
      - "4000:4000"
    volumes:
      - ./:/graphql-example
      - /graphql-example/node_modules
    command: npm run prod