FROM  node:17-alpine
WORKDIR /graphql-example/server
COPY package.json .
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
    else npm install --only=production; \
    fi
COPY . ./ 